app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//NAMED ROUTES
Route::get('/',[
    'uses' => 'Auth\AuthController@showLoginForm',
    'as' => 'home'
    ]);

Route::get('register', [
	'uses' => 'UserController@index',
	'as' => 'register'
	]);

$this->get('login', 'Auth\AuthController@showLoginForm');
$this->get('logout', 'Auth\AuthController@logout')->name('userlogout');
$this->post('login', 'Auth\AuthController@postLogin');
$this->get('forgotpassword', 'Auth\AuthController@getForgotPassword')->name('forgotpassword');
$this->post('forgotpassword', 'Auth\AuthController@postForgotPassword');
$this->post('resetpass', 'Auth\AuthController@postResetPassword')->name('resetpass');;


Route::get('store/{id?}',[
    'uses' => 'StoreController@getProductsList',
    'as' => 'store'
    ]);



//RESOURCE ROUTES PUBLIC
Route::resource('user', 'UserController');
Route::resource('cart', 'CartController');
Route::get('distributors/', [
    'uses' => 'CartController@getDistributorsList',
    'as' => 'getdistributors'
    ]);
Route::get('products/', [
    'uses' => 'CartController@getProductsList',
    'as' => 'getproducts'
    ]);
Route::get('products2/', [
    'uses' => 'CartController@getProductsList2',
    'as' => 'getproducts2'
    ]);
Route::get('brands/', [
    'uses' => 'CartController@getBrandsList',
    'as' => 'getbrands'
    ]);
Route::post('checkout/', [
    'uses' => 'CartController@checkout',
    'as' => 'checkout'
    ]);
Route::post('complete/', [
    'uses' => 'CartController@complete',
    'as' => 'complete'
    ]);
Route::get('gethelp/', [
    'uses' => 'UserController@getHelp',
    'as' => 'gethelp'
    ]);
Route::post('gethelp/', [
    'uses' => 'UserController@postHelp',
    'as' => 'gethelp'
    ]);
//RESOURCE ROUTES ADMIN

Route::group(['prefix' => 'admin'], function() {
    Route::get('/',[
        'uses' => 'AdminAuth\AuthController@showLoginForm',
        'as' => 'adminhome'
        ]);
    $this->get('login', 'AdminAuth\AuthController@showLoginForm');
    $this->post('login', 'AdminAuth\AuthController@postLogin');
    $this->get('logout', 'AdminAuth\AuthController@logout')->name('adminlogout');
    Route::resource('muser', 'ManageUserController');
    Route::resource('mdistributor', 'ManageDistributorController');
    Route::resource('mbrand', 'ManageBrandController');
    Route::resource('mproduct', 'ManageProductController');
    Route::resource('mtax', 'ManageTaxController');
    Route::get('distributorproducts/{id}', [
        'uses' => 'ManageDistributorController@getProductsList',
        'as' => 'distributorproducts'
        ]);
    Route::post('toggleproduct', [
        'uses' => 'ManageDistributorController@postToggleProduct',
        'as' => 'toggleproduct'
        ]);
    Route::get('productdistributors/{id}', [
        'uses' => 'ManageProductController@getDistributorList',
        'as' => 'productdistributors'
        ]);
    Route::post('toggledistributor', [
        'uses' => 'ManageProductController@postToggleDistributor',
        'as' => 'toggledistributor'
        ]);
});
Route::group(['prefix' => 'distributor'], function() {
   $this->get('login', 'DistributorAuth\AuthController@showLoginForm')->name('distributorlogin');
   $this->post('login', 'DistributorAuth\AuthController@postLogin');
   $this->get('logout', 'DistributorAuth\AuthController@logout')->name('distributorlogout');
   Route::get('/',[
    'uses' => 'DistributorAuth\AuthController@showLoginForm',
    'as' => 'distributorhome'
    ]);
   Route::get('/dashboard',[
    'uses' => 'DistributorAuth\AuthController@dashboard',
    'as' => 'distributordashboard'
    ]);
   Route::get('/register',[
    'uses' => 'DistributorController@create',
    'as' => 'dregister'
    ]);
   Route::post('/register',[
    'uses' => 'DistributorController@store',
    'as' => 'dregister'
    ]);
   Route::get('/managestock',[
    'uses' => 'DistributorProductController@manageStock',
    'as' => 'managestock'
    ]);
   Route::post('/updatestock',[
    'uses' => 'DistributorProductController@updateStock',
    'as' => 'updatestock'
    ]);

   // Route::resource('distributor', 'DistributorController');
   Route::resource('dproduct', 'DistributorProductController');


   // Route::get('products/', [
   //  'uses' => 'DistributorProductController@getProductsList',
   //  'as' => 'getproducts'
   //  ]);
});
// Route::auth();

resources/views/admin/OLDproduct.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Register With Us </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				@if (!isset($edit))
				{!! Form::open(['method' => 'POST', 'route' => 'admin.mproduct.store', 'class' => 'form-horizontal']) !!}
				@else
				{!! Form::model($product, ['route' => ['admin.mproduct.update', $product->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
				@endif
				
				<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
					{!! Form::label('name', 'Product Name') !!}
					{!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
					<small class="text-danger">{{ $errors->first('name') }}</small>
				</div>	
				
				<div class="form-group{{ $errors->has('strength') ? ' has-error' : '' }}">
					{!! Form::label('strength', 'Strength') !!}
					{!! Form::text('strength', null, ['class' => 'form-control', 'required' => 'required']) !!}
					<small class="text-danger">{{ $errors->first('strength') }}</small>
				</div>	
				
				<div class="form-group{{ $errors->has('pack') ? ' has-error' : '' }}">
					{!! Form::label('pack', 'Pack / Scheme') !!}
					{!! Form::text('pack', null, ['class' => 'form-control', 'required' => 'required']) !!}
					<small class="text-danger">{{ $errors->first('pack') }}</small>
				</div>	
{{-- 				<div class="form-group{{ $errors->has('brand_id') ? ' has-error' : '' }}">
					{!! Form::label('brand_id', 'Select Brand / Company') !!}
					{!! Form::select('brand_id',$brands->lists('name','id'), null, ['id' => 'brand_id', 'class' => 'form-control', 'required' => 'required']) !!}
					<small class="text-danger">{{ $errors->first('brand_id') }}</small>
				</div> --}}
				<div class="btn-group pull-right">
					{!! Form::submit("Submit", ['class' => 'btn btn-success']) !!}
				</div>
				
				{!! Form::close() !!}
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection

resources/views/admin/brand.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Register With Us </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				@if (!isset($edit))
				{!! Form::open(['method' => 'POST', 'route' => 'admin.mbrand.store', 'class' => 'form-horizontal']) !!}
				@else
				{!! Form::model($brand, ['route' => ['admin.mbrand.update', $brand->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
				@endif
				
				<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
				    {!! Form::label('name', 'Brand Name') !!}
				    {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
				    <small class="text-danger">{{ $errors->first('name') }}</small>
				</div>	
				<div class="form-group{{ $errors->has('desc') ? ' has-error' : '' }}">
				    {!! Form::label('desc', 'Description') !!}
				    {!! Form::textarea('desc', null, ['class' => 'form-control ckeditor']) !!}
				    <small class="text-danger">{{ $errors->first('desc') }}</small>
				</div>
				<div class="btn-group pull-right">
					{!! Form::submit("Submit", ['class' => 'btn btn-success']) !!}
				</div>
				
				{!! Form::close() !!}
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection

resources/views/admin/distributor_products.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Add product to Distributor : {{ $distributor->bname }} </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				{!! Form::open(['method' => 'POST', 'route' => 'admin.mdistributor.store', 'class' => 'form-horizontal', 'files' => true]) !!}

				{!! Form::hidden('distributor_id', $distributor->id,['id' => 'distributor_id','data-id' =>  $distributor->id]) !!}
				<table class="table table-hover dataTable" id="disprod">
					<thead>
						<tr>
							<th>Product Name</th>
							<th>Select</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($products as $product)
						<tr>
							<td> {{ $product->name }} </td>
							<td>
								<div class="form-group">
									<div class="checkbox{{ $errors->has('selectprod') ? ' has-error' : '' }}">
										<label for="selectprod">
											{!! Form::checkbox('selectprod', $product->id, (!empty($product->distributors()->find($distributor->id))) ? ( !empty($product->distributors()->find($distributor->id)->first()) ? 'checked' : null ) : null, ['class' => 'selectprod']) !!} 
										</label>
									</div>
									<small class="text-danger">{{ $errors->first('selectprod') }}</small>
								</div>
								<span class="action"></span>								
							</td>
						</tr>
						@endforeach	
					</tbody>
				</table>
				{!! Form::close() !!}
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection
@section('foot')
<script type="text/javascript">
$(document).ready(function() {
	$('#disprod').on('click','.selectprod', function(event) {
		var distributor_id = $('#distributor_id').val();
		var id = $(this).val();
		var toggle = $(this).prop("checked") ? 1 : 0;
		$.ajax({
			url: "{{ route('toggleproduct') }}",
			type: 'POST',
			data: {
				_token: "{{ csrf_token() }}",
				id : id,
				toggle : toggle,
				distributor_id : distributor_id
			},
		})
		.always(function(data) {
			console.log(data);
		});
	});;
});
</script>
@stop

resources/views/admin/login.blade.php
@extends('layouts.public.master_plain')
@section('content')
<div class="login-box" style="margin:2% auto;">
  <div class="login-logo">
    <img src="{{ URL::to('logo.png') }}" alt="" style="width: 200px; height: auto">
    <a href="#"><b>Pharma</b>Tieup</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>
{!! Form::open(['method' => 'POST', 'url' => '/admin/login']) !!}
<div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
    {!! Form::label('username', 'User ID') !!}
    {!! Form::text('username', null, ['class' => 'form-control', 'required' => 'required']) !!}
    <small class="text-danger">{{ $errors->first('username') }}</small>
</div>
<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
    {!! Form::label('password', 'Password') !!}
    {!! Form::password('password',['class' => 'form-control', 'required' => 'required']) !!}
    <small class="text-danger">{{ $errors->first('password') }}</small>
</div>
      <div class="row">
      	<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
      		
      	</div>
        <div class="col-xs-6 col-md-6 col-lg-6 col-sm-6 ">
          <div class="checkbox icheck">
           {{--  <label>
              <input type="checkbox"> Remember Me
            </label> --}}
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4 col-md-4 col-lg-4 col-sm-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
{!! Form::close() !!}
    
      <div class="form-group has-feedback">
{{--         <input type="email" class="form-control" placeholder="Email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div> --}}


  {{--   <a href="#">I forgot my password</a><br>
    <a href="register.html" class="text-center">Register a new membership</a> --}}

  </div>
  <!-- /.login-box-body -->
</div>
@endsection

resources/views/admin/manage_distributor.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Manage Clients </h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table class="table table-hover table-responsive">
       <thead>
         <tr>
           <th>Customer Name</th>
           <th>Email Id</th>
           <th>Actions</th>
           <th>Manage Products</th>
         </tr>
       </thead>
       <tbody>
        @foreach ($distributors as $distributor)
        <tr>
         <td>{{ $distributor->fname . ' ' . $distributor->lname }}</td>
         <td>{{ $distributor->bemail }}</td>
         <td><a href="{{ route('admin.mdistributor.edit',$distributor->id) }}" class="btn btn-warning">EDIT</a></td>
         <td><a href="{{ route('distributorproducts',$distributor->id) }}" class="btn btn-warning">Manage</a></td>
       </tr>
       @endforeach
     </tbody>
   </table>
 </div>
 <!-- /.box-body -->
</div>
</div>
@endsection

resources/views/admin/manage_product.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Register With Us </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<table class="table table-hover table-responsive dataTable">
					<thead>
						<tr>
							<th>Name</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($products as $product)
						<tr>
							<td>{{ $product->name }}</td>
							<td><a href="{{ route('admin.mproduct.edit',$product->id) }}" class="btn btn-warning">EDIT</a></td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection

resources/views/admin/manage_tax.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Register With Us </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<table class="table table-hover table-responsive datatable">
					<thead>
						<tr>
							<th>Name</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($taxs as $tax)
						<tr>
							<td>{{ $tax->name }}</td>
							<td><a href="{{ route('admin.mtax.edit',$tax->id) }}" class="btn btn-warning">EDIT</a></td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection

resources/views/admin/manage_user.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Manage Clients </h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table class="table table-hover table-responsive dataTable">
       <thead>
         <tr>
           <th>Retailer Name</th>
           <th>Customer Name</th>
           <th>Email Id</th>
           <th>Actions</th>
         </tr>
       </thead>
       <tbody>
        @foreach ($users as $user)
        <tr>
         <td>{{ $user->bname }}</td>
         <td>{{ $user->fname . ' ' . $user->lname }}</td>
         <td>{{ $user->bemail }}</td>
         <td><a href="{{ route('admin.muser.edit',$user->id) }}" class="btn btn-warning">EDIT</a><a href="{{ route('admin.muser.destroy',$user->id) }}" class="btn btn-warning">Delete</a></td>
       </tr>
       @endforeach
     </tbody>
   </table>
 </div>
 <!-- /.box-body -->
</div>
</div>
@endsection

resources/views/admin/menu.blade.php
  <aside class="main-sidebar">
  	<!-- sidebar: style can be found in sidebar.less -->
  	<section class="sidebar">
  		<!-- Sidebar user panel -->
{{--   		<div class="user-panel">
  			<div class="pull-left image">
  				<img src="{{ URL::to('theme/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
  			</div>
  			<div class="pull-left info">
  				<p>Admin</p>
  				<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
  			</div>
  		</div> --}}
  		<!-- search form -->
{{--   		<form action="#" method="get" class="sidebar-form">
  			<div class="input-group">
  				<input type="text" name="q" class="form-control" placeholder="Search...">
  				<span class="input-group-btn">
  					<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
  					</button>
  				</span>
  			</div>
  		</form> --}}
    
  		<!-- /.search form -->
  		<!-- sidebar menu: : style can be found in sidebar.less -->
  		<ul class="sidebar-menu">
  			<li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>User Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a href="{{ route('admin.muser.create') }}"><i class="fa fa-circle-o"></i> Create User</a></li>
            <li><a href="{{ route('admin.muser.index') }}"><i class="fa fa-circle-o"></i> Manage User</a></li>
          </ul>
        </li>
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Distributor Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a href="{{ route('admin.mdistributor.create') }}"><i class="fa fa-circle-o"></i> Create Distributor</a></li>
            <li><a href="{{ route('admin.mdistributor.index') }}"><i class="fa fa-circle-o"></i> Manage Distributor</a></li>
          </ul>
        </li>
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Product Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a href="{{ route('admin.mproduct.create') }}"><i class="fa fa-circle-o"></i> Create Product</a></li>
            <li><a href="{{ route('admin.mproduct.index') }}"><i class="fa fa-circle-o"></i> Manage Product</a></li>
          </ul>
        </li>
<li><a href="{{ route('adminlogout') }}"><i class="fa fa-book"></i> <span>Logout</span></a></li>
        
        {{-- 
        TEMPLATE

        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a href=""><i class="fa fa-circle-o"></i> Dashboard             <span class="pull-right-container">
              <small class="label pull-right bg-yellow">12</small>
              <small class="label pull-right bg-green">16</small>
              <small class="label pull-right bg-red">5</small>
            </span></a></li>
            
          </ul>
        </li>


 --}}
        {{-- Multilevel --}}
{{--   			<li class="treeview">
  				<a href="#">
  					<i class="fa fa-share"></i> <span>Multilevel</span>
  					<span class="pull-right-container">
  						<i class="fa fa-angle-left pull-right"></i>
  					</span>
  				</a>
  				<ul class="treeview-menu">
  					<li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
  					<li>
  						<a href="#"><i class="fa fa-circle-o"></i> Level One
  							<span class="pull-right-container">
  								<i class="fa fa-angle-left pull-right"></i>
  							</span>
  						</a>
  						<ul class="treeview-menu">
  							<li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
  							<li>
  								<a href="#"><i class="fa fa-circle-o"></i> Level Two
  									<span class="pull-right-container">
  										<i class="fa fa-angle-left pull-right"></i>
  									</span>
  								</a>
  								<ul class="treeview-menu">
  									<li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
  									<li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
  								</ul>
  							</li>
  						</ul>
  					</li>
  					<li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
  				</ul>
  			</li> --}}
        {{-- Normal Menu Link --}}
{{--   			<li><a href="documentation/index.html"><i class="fa fa-book"></i> <span>Documentation</span></a></li> --}}
{{--   			<li class="header">LABELS</li>
  			<li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
  			<li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
  			<li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li> --}}
  		</ul>
  	</section>
  	<!-- /.sidebar -->
  </aside>

resources/views/admin/product_distributors.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Add Distributor to Product : {{ $product->name }} </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				{!! Form::open(['method' => 'POST', 'route' => 'admin.mproduct.store', 'class' => 'form-horizontal', 'files' => true]) !!}

				{!! Form::hidden('product_id', $product->id,['id' => 'product_id','data-id' =>  $product->id]) !!}
				<table class="table table-hover dataTable">
					<thead>
						<tr>
							<th>Distributor Name</th>
							<th>Select</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($distributors as $distributor)
						<tr>
							<td> {{ $distributor->bname }} </td>
							<td>
								<div class="form-group">
									<div class="checkbox{{ $errors->has('selectprod') ? ' has-error' : '' }}">
										<label for="selectprod">
											{!! Form::checkbox('selectprod', $distributor->id, (!empty($distributor->products()->first())) ? ( !empty($distributor->find(1)->products()->find($product->id)->first()) ? 'checked' : null ) : null, ['class' => 'selectprod']) !!} 
										</label>
									</div>
									<small class="text-danger">{{ $errors->first('selectprod') }}</small>
								</div>
								<span class="action"></span>								
							</td>
						</tr>
						@endforeach	
					</tbody>
				</table>
				{!! Form::close() !!}
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection
@section('foot')
<script type="text/javascript">
$(document).ready(function() {
	$('input.selectprod').on('click', function(event) {
		var product_id = $('#product_id').val();
		var id = $(this).val();
		var toggle = $(this).prop("checked") ? 1 : 0;
		console.log(id);
		$.ajax({
			url: "{{ route('toggledistributor') }}",
			type: 'POST',
			data: {
				_token: "{{ csrf_token() }}",
				id : id,
				toggle : toggle,
				product_id : product_id
			},
		})
		.always(function(data) {
			console.log(data);
		});

		
		
	});;
});
</script>
@stop

resources/views/admin/tax.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Register With Us </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				@if (!isset($edit))
				{!! Form::open(['method' => 'POST', 'route' => 'admin.mtax.store', 'class' => 'form-horizontal']) !!}
				@else
				{!! Form::model($tax, ['route' => ['admin.mtax.update', $tax->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
				@endif
				
				<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
				    {!! Form::label('name', 'Tax Name') !!}
				    {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
				    <small class="text-danger">{{ $errors->first('name') }}</small>
				</div>
				<div class="form-group{{ $errors->has('rate') ? ' has-error' : '' }}">
				    {!! Form::label('rate', 'Tax % / Rate') !!}
				    {!! Form::text('rate', null, ['class' => 'form-control', 'required' => 'required']) !!}
				    <small class="text-danger">{{ $errors->first('rate') }}</small>
				</div>
				<div class="btn-group pull-right">
					{!! Form::reset("Reset", ['class' => 'btn btn-warning']) !!}
					{!! Form::submit("Submit", ['class' => 'btn btn-success']) !!}
				</div>
				
				{!! Form::close() !!}
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection

resources/views/admin/template.blade.php
@extends('layouts.admin.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Register With Us </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection