app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//NAMED ROUTES
Route::get('/',[
    'uses' => 'Auth\AuthController@showLoginForm',
    'as' => 'home'
    ]);

Route::get('register', [
	'uses' => 'UserController@index',
	'as' => 'register'
	]);

$this->get('login', 'Auth\AuthController@showLoginForm');
$this->get('logout', 'Auth\AuthController@logout')->name('userlogout');
$this->post('login', 'Auth\AuthController@postLogin');
$this->get('forgotpassword', 'Auth\AuthController@getForgotPassword')->name('forgotpassword');
$this->post('forgotpassword', 'Auth\AuthController@postForgotPassword');
$this->post('resetpass', 'Auth\AuthController@postResetPassword')->name('resetpass');;


Route::get('store/{id?}',[
    'uses' => 'StoreController@getProductsList',
    'as' => 'store'
    ]);



//RESOURCE ROUTES PUBLIC
Route::resource('user', 'UserController');
Route::resource('cart', 'CartController');
Route::get('distributors/', [
    'uses' => 'CartController@getDistributorsList',
    'as' => 'getdistributors'
    ]);
Route::get('products/', [
    'uses' => 'CartController@getProductsList',
    'as' => 'getproducts'
    ]);
Route::get('products2/', [
    'uses' => 'CartController@getProductsList2',
    'as' => 'getproducts2'
    ]);
Route::get('brands/', [
    'uses' => 'CartController@getBrandsList',
    'as' => 'getbrands'
    ]);
Route::post('checkout/', [
    'uses' => 'CartController@checkout',
    'as' => 'checkout'
    ]);
Route::post('complete/', [
    'uses' => 'CartController@complete',
    'as' => 'complete'
    ]);
Route::get('gethelp/', [
    'uses' => 'UserController@getHelp',
    'as' => 'gethelp'
    ]);
Route::post('gethelp/', [
    'uses' => 'UserController@postHelp',
    'as' => 'gethelp'
    ]);
//RESOURCE ROUTES ADMIN

Route::group(['prefix' => 'admin'], function() {
    Route::get('/',[
        'uses' => 'AdminAuth\AuthController@showLoginForm',
        'as' => 'adminhome'
        ]);
    $this->get('login', 'AdminAuth\AuthController@showLoginForm');
    $this->post('login', 'AdminAuth\AuthController@postLogin');
    $this->get('logout', 'AdminAuth\AuthController@logout')->name('adminlogout');
    Route::resource('muser', 'ManageUserController');
    Route::resource('mdistributor', 'ManageDistributorController');
    Route::resource('mbrand', 'ManageBrandController');
    Route::resource('mproduct', 'ManageProductController');
    Route::resource('mtax', 'ManageTaxController');
    Route::get('distributorproducts/{id}', [
        'uses' => 'ManageDistributorController@getProductsList',
        'as' => 'distributorproducts'
        ]);
    Route::post('toggleproduct', [
        'uses' => 'ManageDistributorController@postToggleProduct',
        'as' => 'toggleproduct'
        ]);
    Route::get('productdistributors/{id}', [
        'uses' => 'ManageProductController@getDistributorList',
        'as' => 'productdistributors'
        ]);
    Route::post('toggledistributor', [
        'uses' => 'ManageProductController@postToggleDistributor',
        'as' => 'toggledistributor'
        ]);
});
Route::group(['prefix' => 'distributor'], function() {
   $this->get('login', 'DistributorAuth\AuthController@showLoginForm')->name('distributorlogin');
   $this->post('login', 'DistributorAuth\AuthController@postLogin');
   $this->get('logout', 'DistributorAuth\AuthController@logout')->name('distributorlogout');
   Route::get('/',[
    'uses' => 'DistributorAuth\AuthController@showLoginForm',
    'as' => 'distributorhome'
    ]);
   Route::get('/dashboard',[
    'uses' => 'DistributorAuth\AuthController@dashboard',
    'as' => 'distributordashboard'
    ]);
   Route::get('/register',[
    'uses' => 'DistributorController@create',
    'as' => 'dregister'
    ]);
   Route::post('/register',[
    'uses' => 'DistributorController@store',
    'as' => 'dregister'
    ]);
   Route::get('/managestock',[
    'uses' => 'DistributorProductController@manageStock',
    'as' => 'managestock'
    ]);
   Route::post('/updatestock',[
    'uses' => 'DistributorProductController@updateStock',
    'as' => 'updatestock'
    ]);

   // Route::resource('distributor', 'DistributorController');
   Route::resource('dproduct', 'DistributorProductController');


   // Route::get('products/', [
   //  'uses' => 'DistributorProductController@getProductsList',
   //  'as' => 'getproducts'
   //  ]);
});
// Route::auth();

app/Distributor.php
<?php

namespace App;

// use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Distributor extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
    'fname',
    'lname',
    'username',
    'password',
    'bname',
    'bphone1',
    'bphone2',
    'bphone3',
    'bmobile',
    'bfax',
    'bemail',
    'vat',
    'baddr1',
    'baddr2',
    'baddr3',
    'baddr4',
    'bcity',
    'bstate',
    'bcountry',
    'internal_notes',
    'bank_name',
    'bank_accname',
    'bank_type',
    'bank_branch',
    'bank_ifsc',
    'drug_lic_no',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    'password', 'remember_token',
    ];
   /**
    * Distributor belongs to Products.
    *
    * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
    */
   public function products()
   {
       // belongsTo(RelatedModel, foreignKey = products_id, keyOnRelatedModel = id)
       return $this->belongsToMany('App\Product', 'distributor_product', 'distributor_id','product_id')->withPivot('quantity','purchase_rate','mrp','vat','tax','cash_discount','net_amount','scheme');
   }
 }

app/Http/Controllers/DistributorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Distributor;
use App\Product;
use Session;
class DistributorController extends Controller
{
     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('distributor.distributor');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $input['bemail'] = trim($input['bemail']);
        $input['password'] = bcrypt($input['password']);

        $distributor = Distributor::create($input);
        Session::flash('message', 'Registeration was Successfull!'); 
        return redirect()->route('distributorhome');
    }
}

resources/views/distributor/brand_product.blade.php
@extends('layouts.distributor.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Manage Products</h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<table class="table table-hover table-responsive dataTable">
					<thead>
						<tr>
							<th>Name</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($brands as $brand)
						<tr>
							<td>{{ $brand->name }}</td>
							<td><a href="{{ route('distributor.dproduct.show',$brand->id) }}" class="btn btn-warning">Show Products</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection

resources/views/distributor/distributor.blade.php
@extends('layouts.distributor.master_plain')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Register With Us </h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        {!! Form::open(['route' => 'dregister', 'class' => 'form-horizontal']) !!}
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Distributor Details</h3>
            </div>
            <div class="panel-body">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group{{ $errors->has('bname') ? ' has-error' : '' }}">
                  {!! Form::label('bname', 'Distributor Name') !!}
                  {!! Form::text('bname', null, ['class' => 'form-control', 'required' => 'required']) !!}
                  <small class="text-danger">{{ $errors->first('bname') }}</small>
                </div>
                <div class="form-group{{ $errors->has('vat') ? ' has-error' : '' }}">
                  {!! Form::label('vat', 'VAT TIN No') !!}
                  {!! Form::text('vat', null, ['class' => 'form-control', 'required' => 'required']) !!}
                  <small class="text-danger">{{ $errors->first('vat') }}</small>
                </div>
                <div class="form-group{{ $errors->has('drug_lic_no') ? ' has-error' : '' }}">
                    {!! Form::label('drug_lic_no', 'Drug Lic No') !!}
                    {!! Form::text('drug_lic_no', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    <small class="text-danger">{{ $errors->first('drug_lic_no') }}</small>
                </div>
              </div>
            </div>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Distributor Bank Details</h3>
            </div>
            <div class="panel-body">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group{{ $errors->has('bank_name') ? ' has-error' : '' }}">
                    {!! Form::label('bank_name', 'Bank Name') !!}
                    {!! Form::text('bank_name', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    <small class="text-danger">{{ $errors->first('bank_name') }}</small>
                </div>  
                <div class="form-group{{ $errors->has('bank_accname') ? ' has-error' : '' }}">
                    {!! Form::label('bank_accname', 'Acc Name') !!}
                    {!! Form::text('bank_accname', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    <small class="text-danger">{{ $errors->first('bank_accname') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bank_type') ? ' has-error' : '' }}">
                    {!! Form::label('bank_type', 'Acc Type') !!}
                    {!! Form::select('bank_type',["CURRENT"=>"CURRENT","SAVINGS"=>"SAVINGS",], null, ['id' => 'bank_type', 'class' => 'form-control', 'required' => 'required']) !!}
                    <small class="text-danger">{{ $errors->first('bank_type') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bank_branch') ? ' has-error' : '' }}">
                    {!! Form::label('bank_branch', 'Branch Name') !!}
                    {!! Form::text('bank_branch', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    <small class="text-danger">{{ $errors->first('bank_branch') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bank_ifsc') ? ' has-error' : '' }}">
                    {!! Form::label('bank_ifsc', 'IFSC Code') !!}
                    {!! Form::text('bank_ifsc', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    <small class="text-danger">{{ $errors->first('bank_ifsc') }}</small>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Your Personal Details</h3>
            </div>
            <div class="panel-body">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group{{ $errors->has('fname') ? ' has-error' : '' }}">
                  {!! Form::label('fname', 'First Name') !!}
                  {!! Form::text('fname', null, ['class' => 'form-control', 'required' => 'required']) !!}
                  <small class="text-danger">{{ $errors->first('fname') }}</small>
                </div>
                <div class="form-group{{ $errors->has('lname') ? ' has-error' : '' }}">
                  {!! Form::label('lname', 'Last Name') !!}
                  {!! Form::text('lname', null, ['class' => 'form-control', 'required' => 'required']) !!}
                  <small class="text-danger">{{ $errors->first('lname') }}</small>
                </div>
              </div>
            </div>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Distributor Contact Details</h3>
            </div>
            <div class="panel-body">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group{{ $errors->has('bphone1') ? ' has-error' : '' }}">
                  {!! Form::label('bphone1', 'Landline No #1') !!}
                  {!! Form::number('bphone1', null, ['class' => 'form-control']) !!}
                  <small class="text-danger">{{ $errors->first('bphone1') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bphone2') ? ' has-error' : '' }}">
                  {!! Form::label('bphone2', 'Landline No #2') !!}
                  {!! Form::number('bphone2', null, ['class' => 'form-control']) !!}
                  <small class="text-danger">{{ $errors->first('bphone2') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bphone3') ? ' has-error' : '' }}">
                  {!! Form::label('bphone3', 'Landline No #3') !!}
                  {!! Form::number('bphone3', null, ['class' => 'form-control']) !!}
                  <small class="text-danger">{{ $errors->first('bphone3') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bmobile') ? ' has-error' : '' }}">
                  {!! Form::label('bmobile', 'Mobile No') !!}
                  {!! Form::number('bmobile', null, ['class' => 'form-control', 'required' => 'required']) !!}
                  <small class="text-danger">{{ $errors->first('bmobile') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bfax') ? ' has-error' : '' }}">
                  {!! Form::label('bfax', 'Fax No') !!}
                  {!! Form::text('bfax', null, ['class' => 'form-control']) !!}
                  <small class="text-danger">{{ $errors->first('bfax') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bemail') ? ' has-error' : '' }}">
                  {!! Form::label('bemail', 'Email address') !!}
                  {!! Form::email('bemail', null, ['class' => 'form-control', 'required' => 'required', 'placeholder' => 'eg: foo@bar.com']) !!}
                  <small class="text-danger">{{ $errors->first('bemail') }}</small>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Login Details</h3>
            </div>
            <div class="panel-body">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
                  {!! Form::label('username', 'Username') !!}
                  {!! Form::text('username', null, ['class' => 'form-control', 'required' => 'required']) !!}
                  <small class="text-danger">{{ $errors->first('username') }}</small>
                </div>
                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                  {!! Form::label('password', 'Password') !!}
                  {!! Form::password('password', ['class' => 'form-control', 'required' => 'required']) !!}
                  <small class="text-danger">{{ $errors->first('password') }}</small>
                </div>
              </div>
            </div>
          </div>
          
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Distributor Address</h3>
            </div>
            <div class="panel-body">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group{{ $errors->has('baddr1') ? ' has-error' : '' }}">
                  {!! Form::label('baddr1', 'Address #1') !!}
                  {!! Form::text('baddr1', null, ['class' => 'form-control']) !!}
                  <small class="text-danger">{{ $errors->first('baddr1') }}</small>
                </div>
                <div class="form-group{{ $errors->has('baddr2') ? ' has-error' : '' }}">
                  {!! Form::label('baddr2', 'Address #2') !!}
                  {!! Form::text('baddr2', null, ['class' => 'form-control']) !!}
                  <small class="text-danger">{{ $errors->first('baddr2') }}</small>
                </div>
                <div class="form-group{{ $errors->has('baddr3') ? ' has-error' : '' }}">
                  {!! Form::label('baddr3', 'Address #3') !!}
                  {!! Form::text('baddr3', null, ['class' => 'form-control']) !!}
                  <small class="text-danger">{{ $errors->first('baddr3') }}</small>
                </div>
                <div class="form-group{{ $errors->has('baddr4') ? ' has-error' : '' }}">
                  {!! Form::label('baddr4', 'Address #4') !!}
                  {!! Form::text('baddr4', null, ['class' => 'form-control']) !!}
                  <small class="text-danger">{{ $errors->first('baddr4') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bcity') ? ' has-error' : '' }}">
                  {!! Form::label('bcity', 'City') !!}
                  {!! Form::text('bcity', null, ['class' => 'form-control']) !!}
                  <small class="text-danger">{{ $errors->first('bcity') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bstate') ? ' has-error' : '' }}">
                  {!! Form::label('bstate', 'State') !!}
                  {!! Form::text('bstate', null, ['class' => 'form-control', 'required' => 'required']) !!}
                  <small class="text-danger">{{ $errors->first('bstate') }}</small>
                </div>
                <div class="form-group{{ $errors->has('bcountry') ? ' has-error' : '' }}">
                  {!! Form::label('bcountry', 'Country') !!}
                  {!! Form::text('bcountry','India', ['class' => 'form-control', 'required' => 'required']) !!}
                  <small class="text-danger">{{ $errors->first('bcountry') }}</small>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="form-group{{ $errors->has('internal_notes') ? ' has-error' : '' }}">
            {!! Form::label('internal_notes', 'Any Message or Information you wish to state') !!}
            {!! Form::textarea('internal_notes', null, ['class' => 'form-control ']) !!}
            <small class="text-danger">{{ $errors->first('internal_notes') }}</small>
          </div>
        </div>
        <div class="clearfix"></div>
        {!! Form::submit("Register", ['class' => 'btn btn-success btn-block']) !!}
        <div class="btn-group ">
        </div>
        
        {!! Form::close() !!}
      </div>
    </div>
    <!-- /.box-body -->
  </div>
</div>
@endsection

resources/views/distributor/distributor_products.blade.php
@extends('layouts.distributor.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Add product to Distributor : {{ $distributor->bname }} </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				{!! Form::open(['method' => 'POST', 'route' => 'admin.mdistributor.store', 'class' => 'form-horizontal', 'files' => true]) !!}

				{!! Form::hidden('distributor_id', $distributor->id,['id' => 'distributor_id','data-id' =>  $distributor->id]) !!}
				<table class="table table-hover dataTable" id="disprod">
					<thead>
						<tr>
							<th>Product Name</th>
							<th>Select</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($products as $product)
						<tr>
							<td> {{ $product->name }} </td>
							<td>
								<div class="form-group">
									<div class="checkbox{{ $errors->has('selectprod') ? ' has-error' : '' }}">
										<label for="selectprod">
											{!! Form::checkbox('selectprod', $product->id, (!empty($product->distributors()->find($distributor->id))) ? ( !empty($product->distributors()->find($distributor->id)->first()) ? 'checked' : null ) : null, ['class' => 'selectprod']) !!} 
										</label>
									</div>
									<small class="text-danger">{{ $errors->first('selectprod') }}</small>
								</div>
								<span class="action"></span>								
							</td>
						</tr>
						@endforeach	
					</tbody>
				</table>
				{!! Form::close() !!}
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection
@section('foot')
<script type="text/javascript">
$(document).ready(function() {
	$('#disprod').on('click','.selectprod', function(event) {
		var distributor_id = $('#distributor_id').val();
		var id = $(this).val();
		var toggle = $(this).prop("checked") ? 1 : 0;
		$.ajax({
			url: "{{ route('toggleproduct') }}",
			type: 'POST',
			data: {
				_token: "{{ csrf_token() }}",
				id : id,
				toggle : toggle,
				distributor_id : distributor_id
			},
		})
		.always(function(data) {
			console.log(data);
		});
	});;
});
</script>
@stop

resources/views/distributor/manage_brand.blade.php
@extends('layouts.distributor.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Register With Us </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<table class="table table-hover table-responsive datatable">
					<thead>
						<tr>
							<th>Name</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($brands as $brand)
						<tr>
							<td>{{ $brand->name }}</td>
							<td><a href="{{ route('admin.mbrand.edit',$brand->id) }}" class="btn btn-warning">EDIT</a></td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection

resources/views/distributor/manage_distributor.blade.php
@extends('layouts.distributor.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Manage Clients </h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table class="table table-hover table-responsive">
       <thead>
         <tr>
           <th>Customer Name</th>
           <th>Email Id</th>
           <th>Actions</th>
           <th>Manage Products</th>
         </tr>
       </thead>
       <tbody>
        @foreach ($distributors as $distributor)
        <tr>
         <td>{{ $distributor->fname . ' ' . $distributor->lname }}</td>
         <td>{{ $distributor->bemail }}</td>
         <td><a href="{{ route('admin.mdistributor.edit',$distributor->id) }}" class="btn btn-warning">EDIT</a></td>
         <td><a href="{{ route('distributorproducts',$distributor->id) }}" class="btn btn-warning">Manage</a></td>
       </tr>
       @endforeach
     </tbody>
   </table>
 </div>
 <!-- /.box-body -->
</div>
</div>
@endsection

resources/views/distributor/manage_product.blade.php
@extends('layouts.distributor.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Register With Us </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<table class="table table-hover table-responsive dataTable">
					<thead>
						<tr>
							<th>Name</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($products as $product)
						<tr>
							<td>{{ $product->name }}</td>
							<td><a href="{{ route('distributor.dproduct.edit',$product->id) }}" class="btn btn-warning">EDIT</a>
{!! Form::model($product, ['route' => ['distributor.dproduct.destroy', $product->id], 'method' => 'DELETE', 'onsubmit' => ' return confirm("Do you really want to delete this product ?")']) !!}


		
		{!! Form::submit("DELETE", ['class' => 'btn btn-danger']) !!}

{!! Form::close() !!}
								{{-- <a href="{{ route('distributor.dproduct.edit',$product->id) }}" class="btn btn-danger" onclick="">DELETE</a> --}}

							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection

resources/views/distributor/manage_user.blade.php
@extends('layouts.distributor.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Manage Clients </h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table class="table table-hover table-responsive dataTable">
       <thead>
         <tr>
           <th>Retailer Name</th>
           <th>Customer Name</th>
           <th>Email Id</th>
           <th>Actions</th>
         </tr>
       </thead>
       <tbody>
        @foreach ($users as $user)
        <tr>
         <td>{{ $user->bname }}</td>
         <td>{{ $user->fname . ' ' . $user->lname }}</td>
         <td>{{ $user->bemail }}</td>
         <td><a href="{{ route('admin.muser.edit',$user->id) }}" class="btn btn-warning">EDIT</a><a href="{{ route('admin.muser.destroy',$user->id) }}" class="btn btn-warning">Delete</a></td>
       </tr>
       @endforeach
     </tbody>
   </table>
 </div>
 <!-- /.box-body -->
</div>
</div>
@endsection

resources/views/distributor/template.blade.php
@extends('layouts.distributor.master')
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="box box-solid">
		<div class="box-header with-border">
			<h3 class="box-title">Register With Us </h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			</div>
		</div>
		<!-- /.box-body -->
	</div>
</div>
@endsection