app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//NAMED ROUTES
Route::get('/',[
    'uses' => 'Auth\AuthController@showLoginForm',
    'as' => 'home'
    ]);

Route::get('register', [
	'uses' => 'UserController@index',
	'as' => 'register'
	]);

$this->get('login', 'Auth\AuthController@showLoginForm');
$this->get('logout', 'Auth\AuthController@logout')->name('userlogout');
$this->post('login', 'Auth\AuthController@postLogin');
$this->get('forgotpassword', 'Auth\AuthController@getForgotPassword')->name('forgotpassword');
$this->post('forgotpassword', 'Auth\AuthController@postForgotPassword');
$this->post('resetpass', 'Auth\AuthController@postResetPassword')->name('resetpass');;


Route::get('store/{id?}',[
    'uses' => 'StoreController@getProductsList',
    'as' => 'store'
    ]);



//RESOURCE ROUTES PUBLIC
Route::resource('user', 'UserController');
Route::resource('cart', 'CartController');
Route::get('distributors/', [
    'uses' => 'CartController@getDistributorsList',
    'as' => 'getdistributors'
    ]);
Route::get('products/', [
    'uses' => 'CartController@getProductsList',
    'as' => 'getproducts'
    ]);
Route::get('products2/', [
    'uses' => 'CartController@getProductsList2',
    'as' => 'getproducts2'
    ]);
Route::get('brands/', [
    'uses' => 'CartController@getBrandsList',
    'as' => 'getbrands'
    ]);
Route::post('checkout/', [
    'uses' => 'CartController@checkout',
    'as' => 'checkout'
    ]);
Route::post('complete/', [
    'uses' => 'CartController@complete',
    'as' => 'complete'
    ]);
Route::get('gethelp/', [
    'uses' => 'UserController@getHelp',
    'as' => 'gethelp'
    ]);
Route::post('gethelp/', [
    'uses' => 'UserController@postHelp',
    'as' => 'gethelp'
    ]);
//RESOURCE ROUTES ADMIN

Route::group(['prefix' => 'admin'], function() {
    Route::get('/',[
        'uses' => 'AdminAuth\AuthController@showLoginForm',
        'as' => 'adminhome'
        ]);
    $this->get('login', 'AdminAuth\AuthController@showLoginForm');
    $this->post('login', 'AdminAuth\AuthController@postLogin');
    $this->get('logout', 'AdminAuth\AuthController@logout')->name('adminlogout');
    Route::resource('muser', 'ManageUserController');
    Route::resource('mdistributor', 'ManageDistributorController');
    Route::resource('mbrand', 'ManageBrandController');
    Route::resource('mproduct', 'ManageProductController');
    Route::resource('mtax', 'ManageTaxController');
    Route::get('distributorproducts/{id}', [
        'uses' => 'ManageDistributorController@getProductsList',
        'as' => 'distributorproducts'
        ]);
    Route::post('toggleproduct', [
        'uses' => 'ManageDistributorController@postToggleProduct',
        'as' => 'toggleproduct'
        ]);
    Route::get('productdistributors/{id}', [
        'uses' => 'ManageProductController@getDistributorList',
        'as' => 'productdistributors'
        ]);
    Route::post('toggledistributor', [
        'uses' => 'ManageProductController@postToggleDistributor',
        'as' => 'toggledistributor'
        ]);
});
Route::group(['prefix' => 'distributor'], function() {
   $this->get('login', 'DistributorAuth\AuthController@showLoginForm')->name('distributorlogin');
   $this->post('login', 'DistributorAuth\AuthController@postLogin');
   $this->get('logout', 'DistributorAuth\AuthController@logout')->name('distributorlogout');
   Route::get('/',[
    'uses' => 'DistributorAuth\AuthController@showLoginForm',
    'as' => 'distributorhome'
    ]);
   Route::get('/dashboard',[
    'uses' => 'DistributorAuth\AuthController@dashboard',
    'as' => 'distributordashboard'
    ]);
   Route::get('/register',[
    'uses' => 'DistributorController@create',
    'as' => 'dregister'
    ]);
   Route::post('/register',[
    'uses' => 'DistributorController@store',
    'as' => 'dregister'
    ]);
   Route::get('/managestock',[
    'uses' => 'DistributorProductController@manageStock',
    'as' => 'managestock'
    ]);
   Route::post('/updatestock',[
    'uses' => 'DistributorProductController@updateStock',
    'as' => 'updatestock'
    ]);

   // Route::resource('distributor', 'DistributorController');
   Route::resource('dproduct', 'DistributorProductController');


   // Route::get('products/', [
   //  'uses' => 'DistributorProductController@getProductsList',
   //  'as' => 'getproducts'
   //  ]);
});
// Route::auth();

app/Distributor.php
<?php

namespace App;

// use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Distributor extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
    'fname',
    'lname',
    'username',
    'password',
    'bname',
    'bphone1',
    'bphone2',
    'bphone3',
    'bmobile',
    'bfax',
    'bemail',
    'vat',
    'baddr1',
    'baddr2',
    'baddr3',
    'baddr4',
    'bcity',
    'bstate',
    'bcountry',
    'internal_notes',
    'bank_name',
    'bank_accname',
    'bank_type',
    'bank_branch',
    'bank_ifsc',
    'drug_lic_no',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    'password', 'remember_token',
    ];
   /**
    * Distributor belongs to Products.
    *
    * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
    */
   public function products()
   {
       // belongsTo(RelatedModel, foreignKey = products_id, keyOnRelatedModel = id)
       return $this->belongsToMany('App\Product', 'distributor_product', 'distributor_id','product_id')->withPivot('quantity','purchase_rate','mrp','vat','tax','cash_discount','net_amount','scheme');
   }
 }

app/Http/Controllers/DistributorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Distributor;
use App\Product;
use Session;
class DistributorController extends Controller
{
     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('distributor.distributor');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $input['bemail'] = trim($input['bemail']);
        $input['password'] = bcrypt($input['password']);

        $distributor = Distributor::create($input);
        Session::flash('message', 'Registeration was Successfull!'); 
        return redirect()->route('distributorhome');
    }
}

resources/views/layouts/distributor/foot.blade.php
<!-- jQuery 2.2.3 -->
<script src="{{ URL::to('theme/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
$.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{{ URL::to('theme/bootstrap/js/bootstrap.min.js') }}"></script>
<!-- Morris.js charts -->
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script> --}}
{{-- <script src="{{ URL::to('theme/plugins/morris/morris.min.js') }}"></script> --}}
<!-- Sparkline -->
{{-- <script src="{{ URL::to('theme/plugins/sparkline/jquery.sparkline.min.js') }}"></script> --}}
<!-- jvectormap -->
{{-- <script src="{{ URL::to('theme/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script> --}}
{{-- <script src="{{ URL::to('theme/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script> --}}
<!-- jQuery Knob Chart -->
{{-- <script src="{{ URL::to('theme/plugins/knob/jquery.knob.js') }}"></script> --}}
<!-- daterangepicker -->
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script> --}}
{{-- <script src="{{ URL::to('theme/plugins/daterangepicker/daterangepicker.js') }}"></script> --}}
<!-- datepicker -->
<script src="{{ URL::to('theme/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
{{-- <script src="{{ URL::to('theme/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script> --}}
<!-- Slimscroll -->
{{-- <script src="{{ URL::to('theme/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script> --}}
<!-- FastClick -->
{{-- <script src="{{ URL::to('theme/plugins/fastclick/fastclick.js') }}"></script> --}}
<!-- DATA TABLE -->
<script src="{{ URL::to('theme/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ URL::to('theme/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ URL::to('theme/dist/js/app.min.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{-- <script src="{{ URL::to('theme/dist/js/pages/dashboard.js') }}"></script> --}}
<!-- AdminLTE for demo purposes -->
{{-- <script src="dist/js/demo.js"></script> --}}
<script src="//cdn.ckeditor.com/4.5.10/full/ckeditor.js"></script>
<script type="text/javascript" src="http://cdn.ckeditor.com/4.5.10/full/lang/en.js"></script>
<script type="text/javascript" src="http://cdn.ckeditor.com/4.5.10/full/styles.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
{{-- <script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script> --}}
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
{{-- <script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script> --}}
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
{{-- <script src="{{ URL::to('file_uploader/js/jquery.iframe-transport.js') }}"></script> --}}
<!-- The basic File Upload plugin -->
{{-- <script src="{{ URL::to('file_uploader/js/jquery.fileupload.js') }}"></script> --}}
<!-- The File Upload processing plugin -->
{{-- <script src="{{ URL::to('file_uploader/js/jquery.fileupload-process.js') }}"></script> --}}
<!-- The File Upload image preview & resize plugin -->
{{-- <script src="{{ URL::to('file_uploader/js/jquery.fileupload-image.js') }}"></script> --}}

<!-- The File Upload validation plugin -->
{{-- <script src="{{ URL::to('file_uploader/js/jquery.fileupload-validate.js') }}"></script> --}}
<link href="{{ URL::to('dropzone/basic.min.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ URL::to('dropzone/dropzone.min.css') }}" rel="stylesheet" type="text/css"/>
<script src="{{ URL::to('dropzone/dropzone.js') }}"></script>
<script type="text/javascript">
$(document).ready(function() {
	CKEDITOR.editorConfig = function( config ) {
		config.language = 'en';
		config.uiColor = '#F7B42C';
		config.height = 300;
		config.toolbarCanCollapse = true;
	};

});
</script>
<script>
$(document).ready(function(){
	$('.dataTable').DataTable();
});
</script>

@yield('foot')

resources/views/layouts/distributor/footer.blade.php
<div class="pull-right hidden-xs">
    <b>Version</b> 1.0 | 
    {{-- Designed By <strong><a href="http://exits.in">EXiTS Consultancy Services</a>.</strong> --}}
  </div>
  <strong>Copyright &copy; 2016 <a href="http://sinetworks.in">PharmaTieup</a>.</strong> All rights
  reserved.
	

resources/views/layouts/distributor/head.blade.php
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>@yield('title')</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{{ URL::to('theme/bootstrap/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ URL::to('theme/dist/css/AdminLTE.min.css') }}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ URL::to('theme/dist/css/skins/skin-blue.min.css') }}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ URL::to('theme/plugins/iCheck/flat/blue.css') }}">
  <!-- Morris chart -->
  <link rel="stylesheet" href="{{ URL::to('theme/plugins/morris/morris.css') }}">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{{ URL::to('theme/plugins/jvectormap/jquery-jvectormap-1.2.2.css') }}">
  <!-- Date Picker -->
  <link rel="stylesheet" href="{{ URL::to('theme/plugins/datepicker/datepicker3.css') }}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{ URL::to('theme/plugins/daterangepicker/daterangepicker.css') }}">
  <!-- bootstrap wysihtml5 - text editor -->
 <link rel="stylesheet" href="{{ URL::to('theme/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
 <link rel="stylesheet" href="{{ URL::to('theme/plugins/datatables/dataTables.bootstrap.css') }}">
<link rel="stylesheet" type="text/css" href="http://cdn.ckeditor.com/4.5.10/full/skins/moono/editor.css">
  <link rel="stylesheet" href="{{ URL::to('theme/dist/css/styles.css') }}">
{{-- <script src="{{ URL::to('fine-uploader/fine-uploader.core.min.js') }}"></script> --}}
{{-- <link href="{{ URL::to('file_uploader/css/jquery.fileupload.css') }}" rel="stylesheet" type="text/css"/> --}}


 
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  @yield('head')

resources/views/layouts/distributor/master.blade.php
<!DOCTYPE html>
<html>
<head>
  @include('layouts.distributor.head')
</head>
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <header class="main-header">
      <!-- Logo -->
      <a href="#" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>P</b>Ti</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Pharma</b>Tieup</span>
      </a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
          <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <!-- Messages: style can be found in dropdown.less-->
            {{-- @include('layouts.distributor.message_nav') --}}
            <!-- Notifications: style can be found in dropdown.less -->
            {{-- @include('layouts.distributor.notification_nav') --}}
            <!-- Tasks: style can be found in dropdown.less -->
            {{-- @include('layouts.distributor.task_nav') --}}
            <!-- User Account: style can be found in dropdown.less -->
            {{-- @include('layouts.distributor.profile_nav') --}}
            <!-- Control Sidebar Toggle Button -->
 {{--            <li>
              <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
            </li> --}}
          </ul>
        </div>
      </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    @include('layouts.distributor.menu')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          @yield('page_title')
          <small>@yield('page_title_small')</small>
        </h1>
        <ol class="breadcrumb">
          @yield('breadcrumbs')
       {{--  <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
       <li class="active">Dashboard</li> --}}
     </ol>
   </section>

   <!-- Main content -->
   <section class="content">
    <!-- Main row -->
    <div class="row">
      @yield('content')

      

    </div>
    <!-- /.row (main row) -->

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<footer class="main-footer">
 @include('layouts.distributor.footer')
</footer>
<!-- Control Sidebar -->
@include('layouts.distributor.rsidebar')
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
@include('layouts.distributor.foot')
</body>
</html>
    {{--  <div class="box box-solid">
            <div class="box-header with-border">
              <i class="fa fa-text-width"></i>

              <h3 class="box-title">Block </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              
            </div>
            <!-- /.box-body -->
          </div> --}}

resources/views/layouts/distributor/master_plain.blade.php
<!DOCTYPE html>
<html>
<head>
  @include('layouts.distributor.head')
</head>
<body class="skin-blue  wysihtml5-supported sidebar-collapse ">
  <div class="wrapper">

    <header class="main-header">
      <!-- Logo -->
      <a href="#" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>P</b>Ti</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Pharma</b>Tieup</span>
      </a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->


        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">

          </ul>
        </div>
      </nav>
    </header>


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <!-- Main content -->
      <section class="content">
        <!-- Main row -->
        <div class="row">
         @yield('content')
       </div>
       <!-- /.row (main row) -->
     </section>
     <!-- /.content -->
   </div>
   <!-- /.content-wrapper -->
   <footer class="main-footer">
     @include('layouts.distributor.footer')
   </footer>
 </div>
 <!-- ./wrapper -->
 @include('layouts.distributor.foot')
</body>
</html>
{{--  <div class="box box-solid">
<div class="box-header with-border">
  <i class="fa fa-text-width"></i>

  <h3 class="box-title">Block </h3>
</div>
<!-- /.box-header -->
<div class="box-body">

</div>
<!-- /.box-body -->
</div> --}}

resources/views/layouts/distributor/menu.blade.php
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
{{--      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{ URL::to('theme/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Admin</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div> --}}
      <!-- search form -->
{{--      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
        </div>
      </form> --}}
    
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
{{--         <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>User Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a href="{{ route('admin.muser.create') }}"><i class="fa fa-circle-o"></i> Create User</a></li>
            <li><a href="{{ route('admin.muser.index') }}"><i class="fa fa-circle-o"></i> Manage User</a></li>
          </ul>
        </li> --}}

    <li><a href="{{ route('distributor.dproduct.create') }}"><i class="fa fa-plus"></i> <span>Add Product</span></a></li>
    <li><a href="{{ route('distributor.dproduct.index') }}"><i class="fa fa-list"></i> <span>Manage Products</span></a></li>
    <li><a href="{{ route('managestock') }}"><i class="fa fa-balance-scale"></i> <span>Manage Stock</span></a></li>
    <li><a href="{{ route('distributorlogout') }}"><i class="fa fa-book"></i> <span>Logout</span></a></li>
        
        {{-- 
        TEMPLATE

        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a href=""><i class="fa fa-circle-o"></i> Dashboard             <span class="pull-right-container">
              <small class="label pull-right bg-yellow">12</small>
              <small class="label pull-right bg-green">16</small>
              <small class="label pull-right bg-red">5</small>
            </span></a></li>
            
          </ul>
        </li>


 --}}
        {{-- Multilevel --}}
{{--        <li class="treeview">
          <a href="#">
            <i class="fa fa-share"></i> <span>Multilevel</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
            <li>
              <a href="#"><i class="fa fa-circle-o"></i> Level One
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                <li>
                  <a href="#"><i class="fa fa-circle-o"></i> Level Two
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                  </a>
                  <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
          </ul>
        </li> --}}
        {{-- Normal Menu Link --}}
{{--        <li><a href="documentation/index.html"><i class="fa fa-book"></i> <span>Documentation</span></a></li> --}}
{{--        <li class="header">LABELS</li>
        <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li> --}}
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

resources/views/layouts/distributor/message_nav.blade.php
          <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <!-- end message -->
                </ul>
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>

resources/views/layouts/distributor/notification_nav.blade.php
 <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">10</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li>
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                  </li>
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>

resources/views/layouts/distributor/task_nav.blade.php
<li class="dropdown tasks-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li><!-- Task item -->
                    <a href="#">
                      <h3>
                        Design some buttons
                        <small class="pull-right">20%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer">
                <a href="#">View all tasks</a>
              </li>
            </ul>
          </li>